## OOPS IN PYTHON 

In [195]:
" IN PROCEDURAL PROGRAM"

student =[]
def add_student(name, classs , rollno):
    student.append({"name" : name , "classs" : classs , " rollno" : rollno}) 

def display():
    for i in range(0,len(student) ) :
        print(f" name {student[i]['name']}  class : {student[i]['classs']}   rollno. {student[i][' rollno']}")
    


In [196]:
add_student('yashraj singh ', 12 ,21 )
display()


 name yashraj singh   class : 12   rollno. 21


### through using class and obejects 

In [197]:
class student :
    def __init__(self , name ,clas ,rollno) :
        self.name = name 
        self.clas = clas 
        self.rollno = rollno
    def display() :
        
        print("f name : {self.name} clas : {self.clas} rollno :{self.roll}")

class student_manager :
    def __init__ (self):
        self.students =[]



classes and objects :

In [198]:
class student :
    def __init__(self , name ,age ):

        self.name = name 
        self.age = age 
       

yashraj = student( "yahsraj singh " , 21 )
yashraj.name 
yashraj.age 

type(student )

type

In [199]:
class student :
    school = "army public school "
    def __init__(self , name ,age ):

        self.name = name 
        self.age = age 
       

yashraj = student( "yahsraj singh " , 21 )
yashraj.name 
yashraj.age 
yashraj.school
student.school 


'army public school '

In [200]:
student.school

'army public school '

In [201]:
yashraj2 = student( "yashraj2" , 42 )
yashraj2.name 
yashraj2.age 

42

In [202]:
yashraj == yashraj2

False

In [203]:
type(yashraj)

__main__.student

In [204]:
yashraj.school = "banar "

In [205]:
yashraj.school 


'banar '

In [206]:
student.school 

'army public school '

#### instance methods and class methods 

In [207]:
class student :
    school = "army public school "
    def __init__(self , name ,age ):

        self.name = name 
        self.age = age 

    def __str__(self) :
        return f'hello my name {self.name} and age is {self.age}'
    def display(self) :
        print(f'name : {self.name} age :{self.age}')

In [208]:
ram = student("ram" , 31 )
shyam = student ("shyam" , 41 )

In [209]:
ram.display()

name : ram age :31


In [210]:
shyam.display()

name : shyam age :41


In [211]:
print(shyam)

hello my name shyam and age is 41


In [212]:
shyam.__str__() # we can customize this 

'hello my name shyam and age is 41'

class methods 

In [213]:
class student :
    school = "army public school "
    def __init__(self , name ,age ):

        self.name = name 
        self.age = age 

    def __str__(self) :
        return f'hello my name {self.name} and age is {self.age} and my school is {self.school}'
    def display(self) :
        print(f'name : {self.name} age :{self.age}')
    
    @classmethod 
    def chnage_school(cls , names ) :
        cls.school = names 


In [214]:
aman =student("name " , 23 ) 
print (aman)

hello my name name  and age is 23 and my school is army public school 


In [215]:
aman.school = " banar "

In [216]:
print (aman)

hello my name name  and age is 23 and my school is  banar 


In [217]:
class student  :
    school = "Army puclic school "

    def __init__(self, name , age ):
        self.name = name 
        self.age  =age 

    def display(self ):
        print(f'Name : {self.name} and  Age : {self.age }')

    def __str__ (self):
        return f"hello {self.name }with {self.age }"
    
    @classmethod
    def schooln(cls,name) :
        cls.school = name 
    

        


In [218]:
ram =student("ram " , 24 )
ram.name 


'ram '

In [219]:
ram.age

24

In [220]:
class student  :
    school = "Army puclic school "

    def __init__(self, name , age ):
        self.__name = name 
        self.age  =age 

    def display(self ):
        print(f'Name : {self.__name } and with age :{self.age}')

    def __str__ (self):
        return f"hello {self.__name} with {self.age }"
    
    @classmethod
    def schooln(cls,name) :
        cls.school = name 
    

        


In [221]:
yash = student ("yash" , 19 )

In [222]:
yash.name ## private that's why producing  error 

AttributeError: 'student' object has no attribute 'name'

In [ ]:
yash._student__name ## can be acesss public 

### private 

In [ ]:
class student  :
    school = "Army puclic school "

    def __init__(self, name , age ):
        self._name = name 
        self.age  =age 

    def display(self ):
        print(f'Name : {self._name } and with age :{self.age}')

    def __str__ (self):
        return f"hello {self._name} with {self.age }"
    
    @classmethod
    def schooln(cls,name) :
        cls.school = name 

In [ ]:
annu = student("annu" , 19 ) 
annu.name ## giving error (private )

In [ ]:
annu ._name 

 ## importance 
 1. encapsulation 

In [ ]:
class bank_account :
    def __init__(self,balance):
        self.__balance = balance 
    
    def deposit(self,amount):
        self.__balance += amount
    
    def get_balance(self) :
        print(f" your balance is {self.__balance}")

    

In [ ]:
account1 = bank_account(500)

account1.deposit(1000)

account1.get_balance()

In [ ]:
account1.__balance ## giving error 

## security 

In [ ]:
class login :
    def __init__(self , username , password) :
        self.username = username 
        self.__password  = password 

    def check_password (self,input):
        if  self.__password == input :
            return f'your password is correct '
        else :
            return f'false '


In [ ]:
yash = login ("yash" , 23456)
yash.check_password(78975)

In [ ]:
yash.check_password(23456)

## geter and setter  with application in ai ml 

In [ ]:
import numpy as np 


In [ ]:
class Dataloader :
    def __init__(self):
        self._data = None
    
    def get_data(self):
        return self._data
    
    def set_data(self ,arr):
        if not isinstance (arr,np.ndarray) :
            raise TypeError ("data should be in numpy array ")
        
        if arr.ndim != 2 :
            raise ValueError("Input data must be in 2-d ")
        print(f'shape {arr.shape}')
        self._data = arr 

In [223]:
loader =Dataloader()
data =[1,2,34]
loader.set_data(data)

TypeError: data should be in numpy array 

In [225]:
data = np.array([1,2,3,4])
loader.set_data(data)

ValueError: Input data must be in 2-d 

In [226]:
loader.set_data((np.ones((3,4))))

shape (3, 4)


@ property  and  property ()

In [ ]:
class Dataloader :
    def __init__(self ) :
        self._data = None
    
    def get_data(self ):
        return self._data
    
    def set_data (self , arr ):
        if not isinstance(arr,np.adarray)
            raise TypeError("array must be numpy ")

        if arr.ndim !=2 :
            raise ValueError("array should be 2d ")
        print (f' shape : {arr.shape}')
        self._data = arr 
    
    data = property (get_data  , set_data)

In [229]:
loader =Dataloader()

value =np.ones((3,4))
loader.set_data(value )
print(value )

shape (3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [231]:
loader.data = np.ones((4,3))
loader.data ## why because of property ()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

@ property  most appreciated approach 

In [246]:
class Dataloader :
    def __init__(self ) :
        self._data = None
    
    @ property 
    def data(self ):
        return self._data
    
    @data.setter 
    def data(self , arr ):
        if not isinstance(arr,np.ndarray):
            raise TypeError("array must be numpy ")

        if arr.ndim !=2 :
            raise ValueError("array should be 2d ")
        print (f' shape : {arr.shape}')
        self._data = arr 
    
   

In [247]:
loader = Dataloader()
loader.data = np.ones((3,4))
loader.data

 shape : (3, 4)


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])